id: A00C42CAA
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
pechas:
- I2B7E7AE7
- I8E95EEA3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:21.710890
  last_modified_at: 2023-01-04 11:53:21.710902
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I2B7E7AE7/9354: 3F49
  I8E95EEA3/E61C: 3F49
